### ISSUE TITLE
nginx-openidc is incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by mpashka** [tarachandverma/ngx-openidc#7]
nginx-openidc compilation against OpenSSL 1.1.0 fails:
nginx-openidc/src/common-utils/common_utils.c:499:5: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
nginx-openidc/src/common-utils/common_utils.c:841:48: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'
nginx-openidc/src/common-utils/common_utils.c:842:48: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}'

This is because of latest changes in openssl: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes

```
All structures in libssl public header files have been removed so that they are "opaque" to library users. You should use the provided accessor functions instead
...
If you want to access rsa->n you now have to do something like:

    const BIGNUM *n;

    RSA_get0_key(rsa, &n, NULL, NULL);
```

**Comment by tarachandverma** [comment]
I will fix it today.

**Comment by scic** [comment]
The current example is done with nginx 1.8. Since OpenSSL 1.1.0 support is needed for nginx 1.13. Maybe this could be updated as well?

**Comment by gfrankliu** [comment]
I don't see any other nginx third party modules include nginx tarball itself. Why don't we remove nginx-1.8.0.tar.gz from this repo, and let users download nginx directly from nginx.org?
I just tried compiling this module with nginx-1.14.0 from nginx.org without any issues. Haven't tested the resulting binary yet though.

**Comment by thewilli** [comment]
> nginx-openidc compilation against OpenSSL 1.1.0 fails:

[...]

> I will fix it today.

@tarachandverma has this been already fixed?

**Comment by tarachandverma** [comment]
nginx-1.8 was just an example for demo. You can compile with any nginx and it works as I tested.
I will update documentation.

**Comment by tarachandverma** [comment]
@thewilli : it works with openssl 1.1.0 as well.
What's the error you are getting with openssl 1.1.0 ?

**Comment by NunoSav** [comment]
@tarachandverma I'm getting the following errors:

../src/common-utils/common_utils.c:499:5: error: incomplete definition of type 'struct rsa_st'
        rsa->e = e;

../src/common-utils/common_utils.c:500:5: error: incomplete definition of type 'struct rsa_st'
        rsa->n = n;

../src/common-utils/common_utils.c:705:22: error: incomplete definition of type 'struct rsa_st'
                len = BN_bn2bin(rsa->n, buf);

../src/common-utils/common_utils.c:720:22: error: incomplete definition of type 'struct rsa_st'
                len = BN_bn2bin(rsa->e, buf);

../src/common-utils/common_utils.c:841:41: error: invalid application of 'sizeof' to an incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
                cfg->encrypt_ctx = apr_palloc(cfg->p, sizeof(EVP_CIPHER_CTX));

../src/common-utils/common_utils.c:842:41: error: invalid application of 'sizeof' to an incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
                cfg->decrypt_ctx = apr_palloc(cfg->p, sizeof(EVP_CIPHER_CTX));

**Comment by ashishgupta02** [comment]
Any updates on the above issue ? 
I am using the following system:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
OpenSSL 1.1.0g  2 Nov 2017
Nginx: 1.14.0

**Comment by ncpe20012003** [comment]
@tarachandverma Has this been fixed? I'm attempting to compile on Ubuntu 18.04 as well with OpenVPN 1.1.0g.

**Comment by tarachandverma** [comment]
Not yet. I will fix this on this weekend.

**Comment by nunofernandes** [comment]
Also hit by this...
